imu_fusion_filter:
  ros__parameters:
    sample_rate: 100
    use_magnetic_field: true
    orientation_covariance: [ 0.01, 0.0, 0.0,
                              0.0, 0.01, 0.0,
                              0.0, 0.0, 0.01 ]
    angular_velocity_covariance: [ 0.05, 0.0, 0.0,
                                   0.0, 0.05, 0.0,
                                   0.0, 0.0, 0.05 ]
    linear_acceleration_covariance: [ 0.1, 0.0, 0.0,
                                      0.0, 0.1, 0.0,
                                      0.0, 0.0, 0.1 ]
    calibration:
      gyroscope: {
        misalignment: [ 1.0, 0.0, 0.0,
                        0.0, 1.0, 0.0,
                        0.0, 0.0, 1.0 ],
        sensitivity: [ 1.0, 1.0, 1.0 ],
        offset: [ 0.0, 0.0, 0.0 ]
      }
      accelerometer: {
        misalignment: [ 1.0, 0.0, 0.0,
                        0.0, 1.0, 0.0,
                        0.0, 0.0, 1.0 ],
        sensitivity: [ 1.0, 1.0, 1.0 ],
        offset: [ 0.0, 0.0, 0.0 ]
      }
      iron: {
        soft_matrix: [ 1.0, 0.0, 0.0,
                       0.0, 1.0, 0.0,
                       0.0, 0.0, 1.0 ],
        hard_offset: [ 0.0, 0.0, 0.0 ]
      }
    ahrs:
      convention: "ENU"
      gain: 0.5
      gyroscope_range: 2000.0
      acceleration_rejection: 10.0
      magnetic_rejection: 10.0
      recovery_trigger_period: 500

